#!/usr/bin/python3

import os
import subprocess
import tarfile
import tempfile
import traceback
from contextlib import contextmanager
from datetime import datetime
from charmhelpers.core.hookenv import action_set

log_file = None

@contextmanager
def archive_dir():
    """ Open a context with a new temporary directory. This temporary directory
    is made available to child tasks as the SOS_ARCHIVE_DIR environment var.

    When the context closes, the directory is archived, and the archive
    location is added to Juju action output. """
    global log_file
    with tempfile.TemporaryDirectory() as temp_dir:
        name = "sos-" + datetime.now().strftime("%Y%m%d%H%M%S")
        sos_archive_dir = os.path.join(temp_dir, name)
        os.makedirs(sos_archive_dir)
        os.environ["SOS_ARCHIVE_DIR"] = sos_archive_dir
        with open("%s/sos.log" % sos_archive_dir, "w") as log_file:
            yield
        os.chdir(temp_dir)
        tar_path = "/home/ubuntu/%s.tar.gz" % name
        with tarfile.open(tar_path, "w:gz") as f:
            f.add(name)
        action_set({"output": "SOS archive dumped to " + tar_path})

def log(msg, depth=0):
    """ Log a message that will be included in the SOS archive.

    Must be run inside an archive_dir context. """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    prefix = "%s | %s" % (timestamp, "| " * depth)
    for line in str(msg).splitlines():
        log_file.write(prefix + line.rstrip() + "\n")

def run_task(task):
    """ Run a single task. Must be run inside an archive_dir context. """
    log("Running task: " + task)
    process = subprocess.Popen(
        "sos-tasks/" + task,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT
    )
    for line in process.stdout:
        log(line.decode("utf-8"), depth=1)
    exit_code = process.wait()
    if exit_code != 0:
        log("ERROR: %s failed with exit code %d" % (task, exit_code))

def run_all_tasks():
    """ Run all tasks. For the sake of robustness, log and ignore any
    exceptions that occur.

    Must be run inside an archive_dir context. """
    tasks = os.listdir("sos-tasks")
    for task in tasks:
        try:
            run_task(task)
        except:
            log(traceback.format_exc())

def main():
    """ Open an archive context and run all tasks. """
    with archive_dir():
        run_all_tasks()

if __name__ == "__main__":
    main()
